"""create_click_events_table

Revision ID: 522afb7ee8da
Revises: 703f49f2aebe
Create Date: 2026-07-15 15:44:40.154915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '522afb7ee8da'
down_revision: Union[str, Sequence[str], None] = '703f49f2aebe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('click_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('link_id', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=1000), nullable=False),
    sa.Column('referer', sa.String(length=2048), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('browser', sa.String(length=100), nullable=False),
    sa.Column('os', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_click_events_link_id'), 'click_events', ['link_id'], unique=False)
    op.create_index(op.f('ix_click_events_organization_id'), 'click_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_click_events_timestamp'), 'click_events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_click_events_timestamp'), table_name='click_events')
    op.drop_index(op.f('ix_click_events_organization_id'), table_name='click_events')
    op.drop_index(op.f('ix_click_events_link_id'), table_name='click_events')
    op.drop_table('click_events')
    # ### end Alembic commands ###
