"""create_links_table

Revision ID: 703f49f2aebe
Revises: 87d117672d1e
Create Date: 2026-07-13 21:56:43.625616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '703f49f2aebe'
down_revision: Union[str, Sequence[str], None] = '87d117672d1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('original_url', sa.String(length=2048), nullable=False),
    sa.Column('short_code', sa.String(length=50), nullable=False),
    sa.Column('custom_alias', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('click_count', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'custom_alias', name='uq_links_org_alias')
    )
    op.create_index(op.f('ix_links_created_by'), 'links', ['created_by'], unique=False)
    op.create_index(op.f('ix_links_custom_alias'), 'links', ['custom_alias'], unique=False)
    op.create_index(op.f('ix_links_expires_at'), 'links', ['expires_at'], unique=False)
    op.create_index(op.f('ix_links_organization_id'), 'links', ['organization_id'], unique=False)
    op.create_index(op.f('ix_links_short_code'), 'links', ['short_code'], unique=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='userrole', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='userrole', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_index(op.f('ix_links_short_code'), table_name='links')
    op.drop_index(op.f('ix_links_organization_id'), table_name='links')
    op.drop_index(op.f('ix_links_expires_at'), table_name='links')
    op.drop_index(op.f('ix_links_custom_alias'), table_name='links')
    op.drop_index(op.f('ix_links_created_by'), table_name='links')
    op.drop_table('links')
    # ### end Alembic commands ###
