"""add_resource_columns_to_audit_events

Revision ID: df9954df5d7c
Revises: 1ea609ca3704
Create Date: 2026-07-17 20:07:47.321487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df9954df5d7c'
down_revision: Union[str, Sequence[str], None] = '1ea609ca3704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_events', sa.Column('resource_type', sa.String(length=50), nullable=True))
    op.add_column('audit_events', sa.Column('resource_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_audit_events_resource_id'), 'audit_events', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_events_resource_type'), 'audit_events', ['resource_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_events_resource_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_resource_id'), table_name='audit_events')
    op.drop_column('audit_events', 'resource_id')
    op.drop_column('audit_events', 'resource_type')
    # ### end Alembic commands ###
